const checklistTemplates = {
  infrastructure: { label: 'Annex A — Infrastructure Contract', requirements: ['Approved contract', 'Approved plans and drawings', 'Technical specifications', 'Approved Budget for the Contract (ABC)', 'Detailed contract cost breakdown', 'PERT/CPM network diagram'] },
  infrastructure_variation: { label: 'Annex B — Infrastructure Variation Order', requirements: ['Approved change or extra work order', 'Approved original contract', 'Original and revised plans', 'Agency evaluation report and justification', 'Revised PERT/CPM network diagram', 'Original contract cost breakdown', 'Variation order cost breakdown', 'Notice to Proceed', 'Original COA technical evaluation report'] },
  infrastructure_progress: { label: 'Annex C — Infrastructure Progress Accomplishment', requirements: ['Approved contract', 'Approved change or extra work order', 'Approved plans and drawings', 'Technical specifications', 'Statement of work accomplished or progress report', 'Contract and variation order cost breakdowns', 'Certificate of completion and acceptance', 'As-built plans'] },
  consultancy: { label: 'Annex D — Consultancy Services Contract', requirements: ['Approved consultancy contract', 'Terms of Reference', 'Technical and financial proposal', 'Approved Budget for the Contract (ABC)', 'Contract cost breakdown', 'Program of work or project schedule', 'Approved manning schedule', 'Curriculum vitae of consultants and staff'] },
  time_extension: { label: 'Annex E — Infrastructure/Consulting Time Extension', requirements: ['Approved time extension', 'Contractor or consultant request', 'Approved contract', 'Agency evaluation report', 'Grounds certification or report', 'Notice to Proceed', 'Original PERT/CPM network diagram', 'Revised PERT/CPM network diagram', 'COA reports for prior orders', 'Terms of Reference', 'Original and revised manning schedule'] },
  supplies_contract: { label: 'Annex F — Supplies, Materials and Equipment Contract', requirements: ['Approved contract or purchase order', 'Winning bidder technical and financial proposal', 'Technical specifications', 'Approved plans, drawings, or layout', 'Conditions of contract', 'Approved Budget for the Contract (ABC)', 'Certificate of exclusive distributorship'] },
  delivered_goods: { label: 'Annex G — Delivered Supplies, Materials and Equipment', requirements: ['Approved contract or purchase order', 'Sales invoice and delivery receipt', 'Certificate of acceptance', 'Performance or quality test results', 'Contract cost breakdown', 'Approved plans or drawings', 'Brochures or manuals'] },
  janitorial: { label: 'Annex H — Janitorial Services Contract', requirements: ['Approved contract', 'Personnel rates and schedule of work', 'Contract cost breakdown', 'Floor plans of covered areas', 'Personnel wage classification'] },
  security: { label: 'Annex I — Security Services Contract', requirements: ['Approved contract', 'Personnel rates and work schedule', 'Contract cost breakdown', 'Agency personnel requirements', 'Personnel wage classification', 'Agency population information'] },
  maintenance: { label: 'Annex J — Maintenance Services Contract', requirements: ['Approved contract', 'Maintenance service description', 'Contract cost breakdown', 'Visitorial maintenance details', 'Personnel wage classification'] },
  garbage: { label: 'Annex K — Garbage Collection and Disposal', requirements: ['Approved contract', 'Equipment specifications', 'Terms and conditions', 'Dump site or location', 'ABC and contract cost breakdown', 'Route distance measurements', 'Garbage volume estimates', 'Justification and comparative analysis'] },
  property_appraisal: { label: 'Annex M — Appraised Value of Property', requirements: ['Appraisal report', 'Technical description and acquisition details', 'Ownership or registration documents', 'Photographs', 'Inspection or maintenance records'] },
  lease_rental: { label: 'Annex L — Office/Building Lease or Rental', requirements: ['Approved contract', 'Building floor plans', 'Certificate of occupancy', 'Building description', 'Master deed declaration and restrictions'] },
  equipment_rental: { label: 'Annex N — Equipment Rental', requirements: ['Approved contract', 'Equipment technical specifications', 'ABC and contract cost breakdown', 'Equipment utilization evaluation', 'Area of operation data'] },
  lease_purchase: { label: 'Annex O — Equipment Lease-Purchase', requirements: ['Approved contract', 'Equipment description and accessories', 'Contract cost breakdown', 'Lease payment and period document'] },
  repair: { label: 'Annex Q — Repair of Aircraft, Equipment, or Vehicle', requirements: ['Approved contract or job order', 'Technical description', 'Contract cost breakdown', 'Pre-repair evaluation report', 'Service bulletin', 'Waste materials report', 'Repair history'] },
  hauling: { label: 'Annex P — Forwarding, Shipping, or Hauling', requirements: ['Approved contract', 'ABC and contract cost breakdown', 'Transportation technical description', 'Origin, destination, and distance', 'Cargo weight and volume'] },
  price_verification: { label: 'Annex S — Price Verification for Goods', requirements: ['Approved contract or purchase order', 'Sales invoice and delivery receipt', 'Approved item specifications', 'Approved plans or drawings', 'Unit price references', 'Samples, brochures, or photographs', 'Certificate of exclusive distributorship', 'Importation documents'] },
};
const defaultTemplate = 'supplies_contract';
const getChecklistTemplate = (contractType) => checklistTemplates[contractType] || checklistTemplates[defaultTemplate];
module.exports = { checklistTemplates, defaultTemplate, getChecklistTemplate };
